### ISSUE TITLE
DetNet missing within the given codes.

### ISSUE THREAD

**Issue by talefty123** [DoHaiSon/ISDNN#1]
Hi, I have read your paper at [ISDNN: A Deep Neural Network for Channel Estimation in Massive MIMO systems](https://arxiv.org/abs/2410.20110). 

At `Fig 3`, you mentioned of using NMSE estimation for the [DetNet architecture](https://paperswithcode.com/paper/deep-mimo-detection), I am a newbie of applying Machine Learning in Telecommunication at undergrate level, would you kindly give me more in details on how you used the algorithm for the comparision of the two proposed models `ISDNN` and `S-ISDNN` within the paper as I read about the [DetNet](https://paperswithcode.com/paper/deep-mimo-detection), most of it comes from using an entirely differently library as [TensorFlow](https://www.tensorflow.org) whereas yours is [Pytorch](https://pytorch.org).

Thank you for reading, and I wish you have a great day!

**Comment by DoHaiSon** [comment]
Thx for ur asking,
If we use the DetNet repo for comparison, it is not feasible because its purpose is data detection. Therefore, I rewrote a version of it based on the mathematical formulation described in the paper to create a version for result comparison. You can find it in the code I uploaded. The limitation is that DetNet only works with a batch size of 1, and I don't have the time to update this issue, but essentially, it's just a runtime problem.

**Comment by talefty123** [comment]
I appreciate your time for giving out the respond as well as updating the codes despite lack of revision to them in the future. I will take a notice of that you have given out upon the limitation of DetNet to generate my own data based on the code you have provided. Thank you for making the code to be publicly available for everyone (for students and the professors and for the enthusiasts) to reuse and generate the data for different purposes.
